package com.example.recruitmentbot.interview.domain;

public enum InterviewConversationState {
    AWAITING_SLOT_SELECTION,
    HR_PENDING,
    AWAITING_COUNCIL_ASSIGNMENT,
    AWAITING_RESCHEDULE_REASON,
    HR_RESCHEDULE_REVIEW,
    COUNCIL_PENDING,
    COUNCIL_SELECTING_SLOT,
    CANDIDATE_REVIEWING_COUNCIL_SLOT,
    COUNCIL_REJECTED,
    CONFIRMED,
    RESCHEDULE_REQUESTED,
    CANCELLED
}
